"use client";

import { useRef } from "react";
import { toPng } from "html-to-image";
import {
  Download,
  Copy,
  MessageCircle,
} from "lucide-react";

type ResultItem = {
  label: string;
  value: string | number;
};

type Props = {
  calculatorName: string;
  results: ResultItem[];
};

export default function ResultShare({
  calculatorName,
  results,
}: Props) {
  const cardRef =
    useRef<HTMLDivElement>(null);

  const downloadImage =
    async () => {
      if (!cardRef.current) return;

      const dataUrl =
        await toPng(cardRef.current);

      const link =
        document.createElement("a");

      link.download = `${calculatorName
        .toLowerCase()
        .replaceAll(" ", "-")}-result.png`;

      link.href = dataUrl;
      link.click();
    };

  const copyResult =
    async () => {
      const text = `
${calculatorName} Result

${results
  .map(
    (item) =>
      `${item.label}: ${item.value}`,
  )
  .join("\n")}

Generated by DevCalc
`;

      await navigator.clipboard.writeText(
        text,
      );

      alert("Result copied");
    };

  const shareWhatsApp =
    () => {
      const text = `
${calculatorName} Result

${results
  .map(
    (item) =>
      `${item.label}: ${item.value}`,
  )
  .join("\n")}

https://www.devcalc.in
`;

      window.open(
        `https://wa.me/?text=${encodeURIComponent(
          text,
        )}`,
        "_blank",
      );
    };

  return (
    <div className="mt-8">
      {/* Hidden Download Card */}
      <div
        ref={cardRef}
        className="mb-6 rounded-3xl border bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-900"
      >
        <h3 className="text-xl font-bold">
          {calculatorName}
        </h3>

        <div className="mt-4 space-y-2">
          {results.map(
            (item, index) => (
              <div
                key={index}
                className="flex justify-between"
              >
                <span>
                  {item.label}
                </span>

                <strong>
                  {item.value}
                </strong>
              </div>
            ),
          )}
        </div>

        <div className="mt-4 border-t pt-4 text-center text-sm text-slate-500">
          Generated by
          www.devcalc.in
        </div>
      </div>

      <div className="flex flex-wrap gap-3">
        <button
          onClick={downloadImage}
          className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-white hover:bg-blue-700"
        >
          <Download size={18} />
          Download
        </button>

        <button
          onClick={shareWhatsApp}
          className="flex items-center gap-2 rounded-xl bg-green-600 px-4 py-3 text-white hover:bg-green-700"
        >
          <MessageCircle size={18} />
          WhatsApp
        </button>

        <button
          onClick={copyResult}
          className="flex items-center gap-2 rounded-xl border px-4 py-3 hover:bg-slate-100 dark:hover:bg-slate-800"
        >
          <Copy size={18} />
          Copy Result
        </button>
      </div>
    </div>
  );
}