import { Calculator } from "@/src/types/calculator";

export const passwordGenerator: Calculator = {
  slug: "password-generator",

  name: "Password Generator",

  description:
    "Generate strong, secure, and random passwords instantly. Create passwords with uppercase letters, lowercase letters, numbers, and special characters for better online security.",

  category: "Utility",

  isPopular: true,

  seo: {
    title:
      "Password Generator - Create Strong & Secure Random Passwords",

    description:
      "Generate secure random passwords online. Create strong passwords with letters, numbers, and symbols to improve account security and protect your online data.",

    keywords: [
      "password generator",
      "random password generator",
      "secure password generator",
      "strong password generator",
      "complex password generator",
      "custom password generator",
      "password security tool",
      "create strong password",
      "generate secure password",
    ],
  },

  steps: [
    {
      step: 1,
      title: "Choose Password Length",
      description:
        "Select the number of characters you want in your password.",
      icon: "calculator",
    },

    {
      step: 2,
      title: "Select Character Types",
      description:
        "Choose uppercase letters, lowercase letters, numbers, and symbols.",
      icon: "calculator",
    },

    {
      step: 3,
      title: "Generate Password",
      description:
        "Click generate to create a random secure password instantly.",
      icon: "calculator",
    },

    {
      step: 4,
      title: "Copy and Use",
      description:
        "Copy your generated password and use it for your accounts.",
      icon: "result",
    },
  ],

  formula: {
    title: "Password Generation Logic",

    formula:
      "Random Selection From Character Set",

    explanation:
      "A password generator creates passwords by randomly selecting characters from a pool of uppercase letters, lowercase letters, numbers, and symbols. Longer passwords with more character types are generally more secure.",

    example: {
      input:
        "Length = 12, Include Symbols = Yes",

      output:
        "A7#kP9!xL2@m",
    },

    useCases: [
      "Online Accounts",
      "Email Security",
      "Banking Accounts",
      "Social Media",
      "Business Applications",
      "Password Management",
      "Website Logins",
      "Cyber Security",
    ],
  },

  faqs: [
    {
      question:
        "What is a password generator?",
      answer:
        "A password generator creates random passwords using letters, numbers, and symbols to improve security.",
    },

    {
      question:
        "Why should I use a strong password?",
      answer:
        "Strong passwords make it much harder for attackers to access your accounts through guessing or brute-force attacks.",
    },

    {
      question:
        "How long should a password be?",
      answer:
        "A password should ideally contain at least 12 to 16 characters for better security.",
    },

    {
      question:
        "Should I include symbols in my password?",
      answer:
        "Yes. Symbols increase password complexity and improve security.",
    },

    {
      question:
        "Are passwords generated by this tool stored or transmitted over the internet?",
      answer:
        "Generation happens in your browser and the tool does not intentionally submit the generated value to DevCalc. However, this version uses JavaScript Math.random rather than a cryptographically secure random generator, so use a trusted password manager for important accounts.",
    },
  ],
  seoContent: `
    <h2>How to generate a stronger password</h2>
    <p>Choose a length and enable the character groups accepted by the website, then generate a new value. Longer passwords generally resist guessing better than short, complicated-looking ones. For important accounts, prefer at least 16 characters when the service allows it and never reuse the same password.</p>
    <h2>Understand this generator's limitation</h2>
    <p>This tool currently selects characters with JavaScript Math.random(). It is convenient for examples and low-risk use, but it is not a cryptographically secure random source. For banking, primary email, work administration, or other sensitive accounts, use the generator built into a reputable password manager.</p>
    <h2>Character options</h2>
    <p>Uppercase letters, lowercase letters, numbers, and symbols can be included or excluded. Selecting a group adds it to the available character pool; it does not guarantee that every generated password contains at least one character from every selected group. Generate again if a website requires a specific composition.</p>
    <h2>Safer password habits</h2>
    <ul><li>Use a unique password for every account.</li><li>Store passwords in a reputable password manager rather than a plain-text note.</li><li>Enable multi-factor authentication where available.</li><li>Do not share a generated password through an insecure message or publish screenshots containing it.</li></ul>
  `,
};
