export const rashiFaqs = [
  { q: "What is my Rashi?", a: "Your Janma Rashi is the sidereal zodiac sign occupied by the Moon at your birth time. This calculator finds it from your birth date, exact local time and birthplace." },
  { q: "Is Rashi the same as a Western zodiac sign?", a: "Usually not. A common Western zodiac sign is based on the tropical Sun, while Janma Rashi in Vedic astrology is based on the sidereal Moon. The two answers can therefore be different." },
  { q: "Why does the calculator need my birthplace?", a: "The birthplace identifies the correct IANA time zone and its historical UTC offset. That converts your local birth time into the precise instant needed to locate the Moon. The Rashi calculation itself uses the geocentric Moon longitude." },
  { q: "How important is the exact birth time?", a: "The Moon remains in one Rashi for roughly two and a quarter days, so a small time difference usually does not change the answer. It matters when the Moon is close to a sign boundary. The calculator warns you when that is the case." },
  { q: "Which ayanamsha does this Rashi calculator use?", a: "It applies a documented mean Lahiri-style ayanamsha to the astronomical Moon longitude. Different ayanamsha conventions can produce a different result near a boundary, so the calculation details and boundary warning are shown openly." },
  { q: "Can I find Rashi using only my name?", a: "A name-based Rashi is a separate traditional convention often linked to the starting sound of a name. Janma Rashi is determined from the Moon at birth and requires birth details, not a name." },
  { q: "What are Nakshatra and Pada in the result?", a: "The 360-degree sidereal zodiac is divided into 27 Nakshatras, and each Nakshatra has four Padas. The calculator derives both from the same sidereal Moon longitude used for your Rashi." },
  { q: "Is this result suitable for official horoscope matching?", a: "It is a transparent educational calculation, not professional or scientific advice. For marriage matching, naming or other important decisions, confirm accurate birth records and consult a qualified practitioner, especially if a boundary warning appears." },
] as const;
